# Generated by Django 5.2.7 on 2025-10-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('diagnostico', models.TextField()),
                ('fecha_evaluacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
