# Generated by Django 5.2.7 on 2025-10-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(max_length=100, verbose_name='Fase Etapa')),
                ('descripcion', models.TextField(max_length=200, null=True, verbose_name='Descripción Etapa')),
                ('video_url', models.URLField(help_text='Ingresa el enlace del video de Youtube.', verbose_name='Video')),
            ],
        ),
    ]
