# Generated by Django 5.2.7 on 2025-10-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField()),
                ('respuesta_correcta', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
