# Generated by Django 5.2.7 on 2025-10-31 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etapa', '0002_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='etapa',
            field=models.ForeignKey(default=0.0004938271604938272, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='Etapa.etapa'),
            preserve_default=False,
        ),
    ]
