# Generated by Django 5.2.7 on 2025-10-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Docente')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido docente')),
                ('rut', models.CharField(max_length=10, verbose_name='Rut Docente')),
                ('correo', models.CharField(max_length=100, null=True, verbose_name='Correo Docente')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
            ],
        ),
    ]
