# Generated by Django 5.2.7 on 2025-10-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casoClinico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='caso',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='caso',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='caso',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='caso',
            name='rut',
        ),
        migrations.AddField(
            model_name='caso',
            name='Descripción',
            field=models.CharField(default='Descripción no disponible', max_length=300, verbose_name='Descripción'),
        ),
    ]
