# Generated by Django 5.2.7 on 2025-10-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casoClinico', '0002_remove_caso_apellido_remove_caso_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='Descripción',
            field=models.CharField(default='', max_length=300, verbose_name='Descripción'),
        ),
    ]
