# Generated by Django 5.2.7 on 2025-10-31 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categoria', '0001_initial'),
        ('casoClinico', '0003_alter_caso_descripción'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='categoria',
            field=models.ForeignKey(default=0.04, on_delete=django.db.models.deletion.CASCADE, to='Categoria.categoria'),
            preserve_default=False,
        ),
    ]
