# Generated by Django 5.2.7 on 2025-10-31 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0001_initial'),
        ('casoClinico', '0004_caso_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paciente.fichapaciente'),
        ),
    ]
