# Generated by Django 5.2.7 on 2025-10-31 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0001_initial'),
        ('casoClinico', '0005_caso_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Perfil.docente'),
        ),
    ]
