# Generated by Django 5.2.7 on 2025-10-31 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etapa', '0003_pregunta_etapa'),
        ('casoClinico', '0006_caso_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='etapa',
            field=models.ForeignKey(default=0.0004938271604938272, on_delete=django.db.models.deletion.CASCADE, to='Etapa.etapa'),
            preserve_default=False,
        ),
    ]
