# Generated by Django 5.2.7 on 2025-10-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0001_initial'),
        ('casoClinico', '0007_caso_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='casos_clinicos', to='Perfil.estudiante'),
        ),
    ]
