# Generated by Django 5.2.7 on 2025-11-04 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etapa', '0005_alter_etapa_video_url'),
        ('casoClinico', '0007_caso_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Etapa.etapa'),
        ),
    ]
