# Generated by Django 5.2.8 on 2025-11-16 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0001_initial'),
        ('Etapa', '0001_initial'),
        ('Perfil', '0002_alter_administrador_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoclinico',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='casos_clinicos', to='Perfil.estudiante'),
        ),
        migrations.AddField(
            model_name='casoclinico',
            name='etapa',
            field=models.ForeignKey(default=0.04, on_delete=django.db.models.deletion.CASCADE, to='Etapa.etapa'),
            preserve_default=False,
        ),
    ]
