# Generated by Django 5.2.7 on 2025-10-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Examen')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('puntaje_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resultado_final', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_uf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField(max_length=200, null=True, verbose_name='Descripción Examen')),
            ],
        ),
    ]
