# Generated by Django 5.2.7 on 2025-10-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntasExf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta_exf', models.TextField()),
                ('resultado_corregido_exf', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
