# Generated by Django 5.2.7 on 2025-10-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examen', '0002_preguntasexf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreguntasExf',
            new_name='Preguntas_Examen_Final',
        ),
    ]
