# Generated by Django 5.2.7 on 2025-10-31 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examen', '0003_rename_preguntasexf_preguntas_examen_final'),
        ('casoClinico', '0006_caso_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenfinal',
            name='valor_uf',
        ),
        migrations.AddField(
            model_name='examenfinal',
            name='caso',
            field=models.OneToOneField(default=0.0004938271604938272, on_delete=django.db.models.deletion.CASCADE, related_name='examen_final', to='casoClinico.caso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntas_examen_final',
            name='examen_final',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_exf', to='Examen.examenfinal'),
            preserve_default=False,
        ),
    ]
