# Generated by Django 5.2.7 on 2025-10-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examen', '0004_remove_examenfinal_valor_uf_examenfinal_caso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas_examen_final',
            name='resultado_corregido_exf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='preguntas_examen_final',
            name='texto_pregunta_exf',
            field=models.TextField(verbose_name='Pregunta'),
        ),
    ]
